# Generated by Django 3.2.9 on 2022-01-09 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_todo_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-modified']},
        ),
    ]
