# Generated by Django 3.2.9 on 2022-01-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_todo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.IntegerField(choices=[('0', 'Todo'), ('1', 'In Progress'), ('2', 'DONE')], default='0'),
        ),
    ]
