# Generated by Django 3.2.9 on 2022-01-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_todo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('TODO', 'Todo'), ('INPROGRESS', 'In Progress'), ('DONE', 'Done')], default='TODO', max_length=10),
        ),
    ]
